version: "3.8"

services:
  qdrant:
    image: docker.repo.de.service.retloc/qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
  api:
    build:
      context: phishing_api
    # dockerfile: 
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    restart: always

  ui:
    build:
      context: webui
    # dockerfile: 
    ports:
      - "8000:8000"
    depends_on:
      - api
    restart: always

volumes:
  qdrant_data:
    driver: local
